### PR TITLE
Follow up the Redmine version up (3.4 to 4.0)

### LINKED ISSUE #20: not compatible with 4.0.1
hello!
the plugin uses a method that was kicked from bundler: [1]

appearantly this takes effect on redmine 4.0.1

Is there a way someone can fix this - thanks in advance!

Kind Regards,
matt

[1]
```
root@myserver:/my/path/redmine-4.0# bundle exec rake db:migrate RAILS_ENV=production --trace                                                                                            
** Invoke db:migrate (first_time)                                                               
** Invoke db:load_config (first_time)                                                         
** Invoke environment (first_time)                                                                 
** Execute environment                                                         
rake aborted!                                                      
NoMethodError: undefined method `to_prepare' for ActionDispatch::Callbacks:Class
Did you mean?  to_param                                                                       
/var/www/redmine/redmine-4.0/plugins/redmine_local_avatars/init.rb:28:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/var/www/redmine/redmine-4.0/lib/redmine/plugin.rb:173:in `block in load'                     
/var/www/redmine/redmine-4.0/lib/redmine/plugin.rb:164:in `each'
/var/www/redmine/redmine-4.0/lib/redmine/plugin.rb:164:in `load'                     
/var/www/redmine/redmine-4.0/config/initializers/30-redmine.rb:21:in `<top (required)>'     
/var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `load'
/var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `block in load'
/var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `load'
/var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/engine.rb:657:in `block in load_config_initializer'
/var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:170:in `instrument'
/var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/engine.rb:656:in `load_config_initializer'
/var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
/var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/engine.rb:613:in `each' 
/var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/engine.rb:613:in `block in <class:Engine>'
/var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
/var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run' 
/var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'                                        
/usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `each'
/var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `tsort_each_child'
/usr/lib/ruby/2.3.0/tsort.rb:415:in `call'
/usr/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
/usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
/var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
/var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
/var/www/redmine/redmine-4.0/config/environment.rb:14:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/application.rb:337:in `require_environment!'
/var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:238:in `block in invoke_prerequisites'
/var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:236:in `each'
/var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:236:in `invoke_prerequisites'
/var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:238:in `block in invoke_prerequisites'
/var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:236:in `each'
/var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:236:in `invoke_prerequisites'
/var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/gems/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/var/lib/gems/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:22:in `load'
/usr/local/bin/rake:22:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment`
```

### PR DESCRIPTION
**Pull request by syoshim**
Fix #20

### CODE REVIEW

**Comment by kouinkouin** [comment]
Works on 4.0.4 :+1:

**Comment by onlyjob** [comment]
Works on 4.0.1. Please merge.

**Comment by mboremski** [comment]
Can confirm that it works on 4.0.4
**Please merge.**

**Comment by mboremski** [comment]
@dup2 could you merge this one pls?

**Comment by dup2** [comment]
There is #16 for redmine 3.3 compatibility - do we need this also for redmine 4.x? (I'm unfortunately currently locked to an older version that is why I can not try it..)

Or can we just merge this one for 3.4 and 4.x support?

**Comment by syoshim** [comment]
@dup2 There is no need to change #16 for Redmine 4.0.x.
I tested that this changes are also compatible with Redmine 3.3.9.

**Pull request merged**
